################################# Default configuration ###################
# provide your domain here
baseURL = "https://examplesite.com/"
# theme
theme = "dot-hugo"
# site title
title = "Programme 2022"
# default language
defaultContentLanguage = "Fr"
# google analytics
googleAnalytics = "" # paste your analytics ID here. (Ex: UA-123-45)
# unsafe html
[markup.goldmark.renderer]
unsafe = true


############################# Default Parameters ##########################
[params]
# logo is for all page
logo = ""
# logo white is for homepage logo, you can use colorful logo too...
logo_white = ""
# when logo is empty, it will shown your site title

# OpenGraph / Twitter Card metadata
description = "Élections locales, 2022 au Sénégal, Programme des Principaux Candidats"
author = "Code for Senegal"
image = "images/logo.png" # this image will be used as fallback if a page has no image of its own

# customize color
primary_color = "#000"
body_color = "#f9f9f9"
text_color = "#636363"
text_color_dark = "#242738"
white_color = "#ffffff"
light_color = "#f8f9fa"

# font family
font_family = "lato" # Choose font family from : https://fonts.google.com/

# contact form action
contact_form_action = "#" # contact form works with : https://formspree.io


############################## social links ############################## 
[[params.social]]
icon = "ti-github" # themify icon pack : https://themify.me/themify-icons
name = "Github"
link = "https://github.com/Code-for-Senegal"


################################### Franch Language ######################
[Languages.fr]
languageName = "Fr"
languageCode = "fr-fr"
weight = 1
copyright = "Copyright &copy; [Code for Senegal](https://github.com/Code-for-Senegal) 2021"

# banner
[Languages.fr.params.banner]
title = "Programme des Candidats"
subtitle = "Élections locales, 2022 au Sénégal"
bg_image = "images/banner.jpg"
placeholder = "Il suffit de demander ici ou de saisir les termes (Partie, Candidat, Commune)"

# call to action
[Languages.fr.params.cta]
enable = true
title = "Vous n'avez pas trouvé votre candidat?"
content = "Contactez-nous pour plus de détails sur les services supplémentaires et la tarification du travail personnalisé"
# call to action button
[Languages.fr.params.cta.button]
enable = true
label = "Contactez nous"
link = "contact"


################## french navigation #################
[[Languages.fr.menu.main]]
name = "Accueil"
url = "/"
weight = 1

[[Languages.fr.menu.main]]
name = "Faq"
url = "faq"
weight = 2

[[Languages.fr.menu.main]]
name = "contact"
url = "contact"
weight = 3

# Dropdown menu
[[Languages.fr.menu.main]]
weight = 4
name = "candidats"
hasChildren = true

  [[Languages.fr.menu.main]]
  parent = "candidats"
  name = "Parties"
  url = "parties"
  weight = 1

  [[Languages.fr.menu.main]]
  parent = "candidats"
  name = "Coalitions"
  url = "coalitions"
  weight = 2

  [[Languages.fr.menu.main]]
  parent = "candidats"
  name = "Indépendants"
  url = "independants"
  weight = 3
